---
- name: Install common dependencies
  ansible.builtin.apt:
    pkg:
      - acl
      - prometheus-node-exporter
      - btop
      - ca-certificates
      - curl
    update_cache: true
  become: true
