---
- name: Install common dependencies
  ansible.builtin.apt:
    pkg:
      - acl
      - prometheus-node-exporter
      - btop
      - ca-certificates
      - curl
      - python3
      - python3-pip
      - lm-sensors
    update_cache: true
  become: true

- name: Import proxmox common when applicable
  ansible.builtin.include_tasks:
    file: proxmox.yml
  when: "'proxmox' in group_names"
