- name: Common Server
  hosts:
    - vms
    - proxmox
  roles:
    - common

- name: Setup postgres
  hosts:
    - brevgress
  roles:
    - postgres

- name: Setup grafana
  hosts:
    - grafana
  roles:
    - grafana

- name: Docker on vms
  hosts:
    - vms
  roles:
    - docker

- name: Setup uptime_kuma
  hosts:
    - havneboks
  roles:
    - uptime_kuma
