when:
  - event: push
    branch: woodpecker_test

steps:
  - name: build
    image: local/builder

    commands:
      - ansible-playbook --help
      - mkdir /root/.ssh && chmod 0700 /root/.ssh
      - echo $SSH_KEY | base64 --decode >> /root/.ssh/id_rsa
      - chmod 0600 /root/.ssh/id_rsa
      - cd ansible 
      - touch ./.vault_password
      - echo $VAULT_PASSWORD >> ./.vault_password
      - ansible-playbook -i homelab.ini --extra-vars "ansible_sudo_pass=$ansible_password" setup.yml
    secrets: [ SSH_KEY, ansible_password, VAULT_PASSWORD ]
